// Generated by Arc Language Compiler
// Do not edit this file manually

#ifndef ARC_GENERATED_H
#define ARC_GENERATED_H

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>

#ifdef __cplusplus
extern "C" {
#endif

// Function declarations
void arc_test_integer_calculations(void);
void arc_test_comparisons(void);
void arc_test_control_flow(void);
int32_t arc_calculate(int32_t arc_x, int32_t arc_y);
void arc_test_function_calls(void);
int32_t arc_main(void);


#ifdef __cplusplus
}
#endif

#endif // ARC_GENERATED_H
