// Generated by Arc Language Compiler
// Do not edit this file manually

#include "my_test.h"
#include <stdio.h>

// Function implementations
void arc_test_integer_calculations(void) {
    // Line 4
    // Line 5
int arc_a = 15;
    // Line 6
int arc_b = 7;
    // Line 7
int arc_sum = (arc_a + arc_b);
    // Line 8
int arc_diff = (arc_a - arc_b);
    // Line 9
int arc_product = (arc_a * arc_b);
    // Line 10
int arc_quotient = (arc_a / arc_b);
}

void arc_test_comparisons(void) {
    // Line 16
    // Line 17
int arc_x = 20;
    // Line 18
int arc_y = 15;
    // Line 19
int arc_equal = (arc_x == arc_y);
    // Line 20
int arc_greater = (arc_x > arc_y);
    // Line 21
int arc_less = (arc_x < arc_y);
    // Line 22
int arc_greater_equal = (arc_x >= arc_y);
    // Line 23
int arc_less_equal = (arc_x <= arc_y);
}

void arc_test_control_flow(void) {
    // Line 26
    // Line 27
int arc_value = 25;
    // Line 29
if ((arc_value > 20)) {
        // Line 29
        // Line 30
int arc_result = 1;
    }
    else {
        // Line 31
        // Line 32
int arc_result = 0;
    }
    // Line 36
int arc_counter = 0;
    // Line 37
while ((arc_counter < 5)) {
        // Line 37
        // Line 38
(arc_counter = (arc_counter + 1));
    }
}

int32_t arc_calculate(int32_t arc_x, int32_t arc_y) {
    // Line 42
    // Line 43
int arc_result = ((arc_x * 2) + arc_y);
    // Line 44
return arc_result;
}

void arc_test_function_calls(void) {
    // Line 47
    // Line 48
int arc_result1 = arc_calculate(10, 5);
    // Line 49
int arc_result2 = arc_calculate(3, 7);
    // Line 50
int arc_result3 = arc_calculate(arc_result1, arc_result2);
}

int32_t arc_main(void) {
    // Line 53
    // Line 54
arc_test_integer_calculations();
    // Line 55
arc_test_comparisons();
    // Line 56
arc_test_control_flow();
    // Line 57
arc_test_function_calls();
    // Line 58
return 0;
}


// End of generated code
