// Generated by Arc Language Compiler
// Do not edit this file manually

#ifndef ARC_GENERATED_H
#define ARC_GENERATED_H

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>

#ifdef __cplusplus
extern "C" {
#endif

// Function declarations
int32_t arc_test_modules(void);
int32_t arc_main(void);


#ifdef __cplusplus
}
#endif

#endif // ARC_GENERATED_H
