// Generated by Arc Language Compiler
// Do not edit this file manually

#include "output.h"
#include <stdio.h>

// Function implementations
int32_t arc_test_modules(void) {
    // Line 6
    // Line 8
int32_t arc_a = 3;
    // Line 9
int32_t arc_b = 5;
    // Line 10
int32_t arc_result = (arc_a + arc_b);
    // Line 11
return arc_result;
}

int32_t arc_main(void) {
    // Line 14
    // Line 15
int32_t arc_result = arc_test_modules();
    // Line 16
printf("Result: %d\n");
    // Line 18
return 0;
}


// End of generated code
